#####                                           #####
##### SENSITIVITY ANALYSIS FOR BP TRAJECTORIES  #####
#####                                           #####

```{r message=FALSE, warning=FALSE}
##### LOAD PACKAGES
library("ggplot2")
library("tidyr")
library("data.table")
library("lme4")
library("dplyr")
library("sitar")
library("splines")

```

```{r}
##### LOAD DATASET
PFAS <- read.csv("C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/PFAS.csv")

```

```{r}
##### SUBSET ONLY VARIABLES NEEDED FOR LME
LME <- subset(PFAS, select = c(aid, DPP_RAV1, WT_RAV1, DPP_RAV2, WT_RAV2, DPP_RAV3, WT_RAV3, 
                                 DPP_RAV4, WT_RAV4, DPP_SR1, WTK_SR1, DPP_SR2, WTK_SR2, DPP_SR4, 
                                 WTK_SR4, DPP_SR5, WTK_SR5, DPP_SR6, WTK_SR6, DPP_SR8, WTK_SR8, 
                                 DPP_SR9, WTK_SR9, DPP_SR10, WTK_SR10, DPP_SR11, WTK_SR11)) 

colnames(LME)[colnames(LME) == "DPP_RAV1"] <- "DPP_1"
colnames(LME)[colnames(LME) == "DPP_SR1"] <- "DPP_2"
colnames(LME)[colnames(LME) == "DPP_SR2"] <- "DPP_3"
colnames(LME)[colnames(LME) == "DPP_RAV2"] <- "DPP_4"
colnames(LME)[colnames(LME) == "DPP_SR4"] <- "DPP_5"
colnames(LME)[colnames(LME) == "DPP_SR5"] <- "DPP_6"
colnames(LME)[colnames(LME) == "DPP_SR6"] <- "DPP_7"
colnames(LME)[colnames(LME) == "DPP_RAV3"] <- "DPP_8"
colnames(LME)[colnames(LME) == "DPP_SR8"] <- "DPP_9"
colnames(LME)[colnames(LME) == "DPP_SR9"] <- "DPP_10"
colnames(LME)[colnames(LME) == "DPP_SR10"] <- "DPP_11"
colnames(LME)[colnames(LME) == "DPP_SR11"] <- "DPP_12"
colnames(LME)[colnames(LME) == "DPP_RAV4"] <- "DPP_13"
# colnames(LME)[colnames(LME) == "DPP_SR14"] <- "DPP_14"
# colnames(LME)[colnames(LME) == "DPP_SR15"] <- "DPP_15"
# colnames(LME)[colnames(LME) == "DPP_SR16"] <- "DPP_16"


colnames(LME)[colnames(LME) == "WT_RAV1"] <- "WT_1"
colnames(LME)[colnames(LME) == "WTK_SR1"] <- "WT_2"
colnames(LME)[colnames(LME) == "WTK_SR2"] <- "WT_3"
colnames(LME)[colnames(LME) == "WT_RAV2"] <- "WT_4"
colnames(LME)[colnames(LME) == "WTK_SR4"] <- "WT_5"
colnames(LME)[colnames(LME) == "WTK_SR5"] <- "WT_6"
colnames(LME)[colnames(LME) == "WTK_SR6"] <- "WT_7"
colnames(LME)[colnames(LME) == "WTK_SR8"] <- "WT_8"
colnames(LME)[colnames(LME) == "WT_RAV3"] <- "WT_9"
colnames(LME)[colnames(LME) == "WTK_SR9"] <- "WT_10"
colnames(LME)[colnames(LME) == "WTK_SR10"] <- "WT_11"
colnames(LME)[colnames(LME) == "WTK_SR11"] <- "WT_12"
colnames(LME)[colnames(LME) == "WT_RAV4"] <- "WT_13"
# colnames(LME)[colnames(LME) == "WTK_SR14"] <- "WT_14"
# colnames(LME)[colnames(LME) == "WTK_SR15"] <- "WT_15"
# colnames(LME)[colnames(LME) == "WTK_SR16"] <- "WT_16"

col_order <- c("aid", "DPP_1", "DPP_2", "DPP_3", "DPP_4", "DPP_5", "DPP_6", "DPP_7", "DPP_8", 
               "DPP_9", "DPP_10", "DPP_11", "DPP_12", "DPP_13",
               "WT_1", "WT_2", "WT_3", "WT_4", "WT_5", "WT_6", "WT_7", "WT_8", 
               "WT_9", "WT_10", "WT_11", "WT_12", "WT_13")
LME <- LME[, col_order]


##### CONVERT DATASET FROM WIDE TO LONG FORMAT
LME$aid <- as.factor(LME$aid)

# BY DAYS POST INDEX PREGNANCY
LME_L <- gather(LME, DPP, WEIGHT, WT_1:WT_13, factor_key=TRUE)
LME_L <- LME_L[order(LME_L$aid),]
LME_L$DPP <- ifelse(LME_L$DPP == "WT_1", LME_L$DPP_1,
                         ifelse(LME_L$DPP == "WT_2", LME_L$DPP_2,
                         ifelse(LME_L$DPP == "WT_3", LME_L$DPP_3,
                         ifelse(LME_L$DPP == "WT_4", LME_L$DPP_4,
                         ifelse(LME_L$DPP == "WT_5", LME_L$DPP_5,
                         ifelse(LME_L$DPP == "WT_6", LME_L$DPP_6,
                         ifelse(LME_L$DPP == "WT_7", LME_L$DPP_7,
                         ifelse(LME_L$DPP == "WT_8", LME_L$DPP_8,
                         ifelse(LME_L$DPP == "WT_9", LME_L$DPP_9,
                         ifelse(LME_L$DPP == "WT_10", LME_L$DPP_10,
                         ifelse(LME_L$DPP == "WT_11", LME_L$DPP_11,
                         ifelse(LME_L$DPP == "WT_12", LME_L$DPP_12,
                         ifelse(LME_L$DPP == "WT_13", LME_L$DPP_13, NA)))))))))))))
LME_L <- subset(LME_L, select = c(aid, DPP, WEIGHT))
LME_L <- na.omit(LME_L)
LME_L <- LME_L[order(LME_L[,1], LME_L[,2] ),]

```

```{r}
##### ADD A YEARLY SCALE
# LME_L$YR_WT <- ifelse(LME_L$DPP >0 & LME_L$DPP <=0.5, 0.5,
#                          ifelse(LME_L$DPP >0.5 & LME_L$DPP <=1, 1,
#                          ifelse(LME_L$DPP >1 & LME_L$DPP <=2, 2,
#                          ifelse(LME_L$DPP >2 & LME_L$DPP <=3, 3,
#                          ifelse(LME_L$DPP >3 & LME_L$DPP <=4, 4,
#                          ifelse(LME_L$DPP >4 & LME_L$DPP <=5, 5,
#                          ifelse(LME_L$DPP >5 & LME_L$DPP <=6, 6, 
#                          ifelse(LME_L$DPP >6 & LME_L$DPP <=7, 7, 
#                          ifelse(LME_L$DPP >7 & LME_L$DPP <=8, 8,
#                          ifelse(LME_L$DPP >8 & LME_L$DPP <=9, 9, 
#                          ifelse(LME_L$DPP >9 & LME_L$DPP <=10, 10,
#                          ifelse(LME_L$DPP >10 & LME_L$DPP <=11, 11,
#                          ifelse(LME_L$DPP >11 & LME_L$DPP <=12, 12,
#                          ifelse(LME_L$DPP >12 & LME_L$DPP <=13, 13,
#                          ifelse(LME_L$DPP >13 & LME_L$DPP <=14, 14,
#                          ifelse(LME_L$DPP >14 & LME_L$DPP <=15, 15,
#                          ifelse(LME_L$DPP >15 & LME_L$DPP <=16, 16,
#                          ifelse(LME_L$DPP >16 & LME_L$DPP <=210, 17, 0))))))))))))))))))
# summary(LME_L$YR_WT)
# table(LME_L$YR_WT)

LME_L$YR_WT <- ifelse(LME_L$DPP >0 & LME_L$DPP <=2, 1,
                         ifelse(LME_L$DPP >2 & LME_L$DPP <=3, 2,
                         ifelse(LME_L$DPP >3 & LME_L$DPP <=4, 3,
                         ifelse(LME_L$DPP >4 & LME_L$DPP <=5, 4,
                         ifelse(LME_L$DPP >5 & LME_L$DPP <=6, 5,
                         ifelse(LME_L$DPP >6 & LME_L$DPP <=7, 6, 
                         ifelse(LME_L$DPP >7 & LME_L$DPP <=8, 7, 
                         ifelse(LME_L$DPP >8 & LME_L$DPP <=9, 8,
                         ifelse(LME_L$DPP >9 & LME_L$DPP <=10, 9, 
                         ifelse(LME_L$DPP >10 & LME_L$DPP <=11, 10,
                         ifelse(LME_L$DPP >11 & LME_L$DPP <=12, 11,
                         ifelse(LME_L$DPP >12 & LME_L$DPP <=13, 12,
                         ifelse(LME_L$DPP >13 & LME_L$DPP <=14, 13,
                         ifelse(LME_L$DPP >14 & LME_L$DPP <=15, 14,
                         ifelse(LME_L$DPP >15 & LME_L$DPP <=16, 15,
                         ifelse(LME_L$DPP >16 & LME_L$DPP <=17, 16, 0))))))))))))))))
summary(LME_L$YR_WT)
table(LME_L$YR_WT)

```


```{r}
##### ADD A "DUP" VARIABLE TO COUNT NUMBER OF DUPLICATED IDs
# LME_L$Time <- length(unique(LME_L$DPP)) == nrow(LME_L)
# LME_L$Time <- sequence(table(LME_L$aid))
# 
# LME_L$Time2 <- ifelse(LME_L$Time == 2, LME_L$YR_WT, 0)
# LME_L$Time3 <- ifelse(LME_L$Time == 3, LME_L$YR_WT, 0)
# LME_L$Time4 <- ifelse(LME_L$Time == 4, LME_L$YR_WT, 0)


LME_L$Time1 <- ifelse(LME_L$YR_WT == 0.5, 0.5, 0)
LME_L$Time2 <- ifelse(LME_L$YR_WT == 1, 1, 0)
LME_L$Time3 <- ifelse(LME_L$YR_WT == 2, 2, 0)
LME_L$Time4 <- ifelse(LME_L$YR_WT == 3, 3, 0)
LME_L$Time5 <- ifelse(LME_L$YR_WT == 4, 4, 0)
LME_L$Time6 <- ifelse(LME_L$YR_WT == 5, 5, 0)
LME_L$Time7 <- ifelse(LME_L$YR_WT == 6, 6, 0)
LME_L$Time8 <- ifelse(LME_L$YR_WT == 7, 7, 0)
LME_L$Time9 <- ifelse(LME_L$YR_WT == 8, 8, 0)
LME_L$Time10 <- ifelse(LME_L$YR_WT == 9, 9, 0)
LME_L$Time11 <- ifelse(LME_L$YR_WT == 10, 10, 0)
LME_L$Time12 <- ifelse(LME_L$YR_WT == 11, 11, 0)
LME_L$Time13 <- ifelse(LME_L$YR_WT == 12, 12, 0)
LME_L$Time14 <- ifelse(LME_L$YR_WT == 13, 13, 0)
LME_L$Time15 <- ifelse(LME_L$YR_WT == 14, 14, 0)
LME_L$Time16 <- ifelse(LME_L$YR_WT == 15, 15, 0)
LME_L$Time17 <- ifelse(LME_L$YR_WT == 16, 16, 0)
LME_L$Time18 <- ifelse(LME_L$YR_WT == 17, 17, 0)

```

```{r}
##### IDENTIFY WEIGHT MEASUREMENT OUTLIERS
outliers <- velout(x = DPP, y = WEIGHT, id = aid, data = LME_L, limit = 4)

# SET 96 WEIGHT OUTLIERS MISSING
LME_LO <- zapvelout(outliers, icode = c(4,5))
LME_LO <- na.omit(LME_LO)

```

```{r}
#http://dpmartin42.github.io/posts/Piecewise-growth

ggplot(aes(x = DPP, y = WEIGHT), data = LME_LO) +
  geom_line(aes(group = aid), color = "gray") + 
  geom_smooth(aes(group = 1), linewidth = 2, color = "blue", se = FALSE) +
  theme_bw() +
  theme(text = element_text(size = 20)) +
  labs(x = "Time postpartum (years)", y = "Weight (kg)")

ggplot(aes(x = DPP, y = WEIGHT), data = LME_L) +
  geom_line(aes(group = aid), color = "gray") + 
  geom_smooth(aes(group = 1), linewidth = 2, color = "blue", se = FALSE) +
  theme_bw() +
  theme(text = element_text(size = 20)) +
  labs(x = "Time postpartum (years)", y = "Weight (kg)")

```

```{r}
##### NATURAL CUBIC SPLINE
##### http://www.science.smith.edu/~jcrouser/SDS293/labs/lab13-r.html
# Get min/max values of age using the range() function
summary(LME_LO$DPP)
dpplims <- c(0.4, 16.6)

# Generate a sequence of age values spanning the range
dpp_grid <- seq(from = min(dpplims), to = max(dpplims))

# Fit a regression spline using natural spline functions
wt.fit <- lm(WEIGHT ~ ns(DPP, df = 2), data = LME_LO)
wt.pred <- predict(wt.fit, newdata = list(DPP = dpp_grid), se = TRUE)

summary(wt.fit)
69.9668 - 1.96*0.3734
69.9668 + 1.96*0.3734

# Compute error bands (1.96*SE)
se_bands <- with(wt.pred, cbind("upper" = fit + 1.96*se.fit, 
                                 "lower" = fit - 1.96*se.fit))


# Plot the natural spline and error bands
ggplot() +
  geom_point(data = LME_LO, aes(x = DPP, y = WEIGHT), col="darkgrey") +
  geom_line(aes(x = dpp_grid, y = wt.pred$fit), color = "blue", lwd = 1) + 
  geom_ribbon(aes(x = dpp_grid, 
                  ymin = se_bands[,"lower"], 
                  ymax = se_bands[,"upper"]), 
              alpha = 0.3) +
  xlim(dpplims) +
  theme_bw() +
  theme(text = element_text(size = 20)) +
  labs(x = "Time post index pregnancy (years)", y = "Weight (kg)")



```


```{r}

# ATTACH THE RANDOM EFFECTS A AND C TO THE DATASET
random_coef <- as.data.frame(ranef(LME_M1)$aid)
random_coef$aid <- as.numeric(rownames(random_coef))
colnames(random_coef)<-c("Intercept","Slope", "aid")
LME_LO <- merge(LME_LO, random_coef, by = "aid")

# ASSESS DISTRIBUTION OF RANDOM EFFECTS
hist(LME_LO$Intercept)
hist(LME_LO$Slope)

```

```{r}
##### SAVE DATASET
LME_LO_FIN <- LME_LO %>% 
  group_by(aid) %>% 
  arrange(YR_WT) %>% 
  filter(row_number()==1)

write.csv(LME_LO_FIN, file = "C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/P2_LME.csv", row.names = T)

```
