#####                                  #####
##### RUN MIXTURES ANALYSIS WITH BKMR  #####
#####                                  #####

```{r message=FALSE, warning=FALSE}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("table1")
library("tidyverse")

```

```{r}
##### LOAD DATASET
PFAS <- read.csv("C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/PFAS.csv")
SITAR <- read.csv("C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/P2_SITAR.csv")

##### MERGE DATASETS
PFAS_WT <- merge(x = SITAR, y = PFAS, by = "aid", all.x = TRUE)
PFAS_WT <- subset(PFAS_WT, select = -c(X.x, X.1, X.y))

```

```{r}
##### LOAD WORKSPACE
load("C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/P2_BKMR.Rdata")

```

```{r}
# ##### CHECK DISTRIBUTION OF OUTCOME VARIABLES
# hist(PFAS_WT$a_wt)
# hist(PFAS_WT$c_wt)

```

```{r}
##### CONVERT VELOCITY TO PERCENT
PFAS_WT$c_wt <- PFAS_WT$c_wt * 100
summary(PFAS_WT$c_wt)

```

```{r}
##### TRANSFORM VARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_WT$age <- PFAS_WT$age_mom_enroll_d
PFAS_WT$menar <- PFAS_WT$mom_firstperiod_12y
PFAS_WT$bmi <- PFAS_WT$bmi_mom_prepreg_d
PFAS_WT$race <- PFAS_WT$race2_mom_epi_epia_d
PFAS_WT$income <- PFAS_WT$gt70k
PFAS_WT$parity <- PFAS_WT$parity_d
PFAS_WT$smoke <- PFAS_WT$smokpreg_final_d
PFAS_WT$married <- PFAS_WT$married_cohab
PFAS_WT$edu <- PFAS_WT$coll_grad
PFAS_WT$fish <- PFAS_WT$fish_d_f1
PFAS_WT$darkmeat <- PFAS_WT$dark_meat_f1

# REFACTOR AND RELABEL 
PFAS_WT$bmi_cat <- ifelse(PFAS_WT$bmi <18.5, 0,
                         ifelse(PFAS_WT$bmi >=18.5 & PFAS_WT$bmi < 25.0, 1, 
                                ifelse(PFAS_WT$bmi >=25.0 & PFAS_WT$bmi < 30.0, 2, 
                                       ifelse(PFAS_WT$bmi >=30.0 & PFAS_WT$bmi < 35.0, 3,
                                              ifelse(PFAS_WT$bmi >=35.0, 4, NA)))))
PFAS_WT$race <- ifelse(PFAS_WT$race == "white", 0,
                      ifelse(PFAS_WT$race == "black", 1,
                             ifelse(PFAS_WT$race == "hispa", 2,
                                    ifelse(PFAS_WT$race == "asian", 3,
                                           ifelse(PFAS_WT$race == "other", 4, 4)))))
PFAS_WT$income <- ifelse(PFAS_WT$income == 1, 1, 0)
PFAS_WT$parity <- ifelse(PFAS_WT$parity == 0, 0,
                        ifelse(PFAS_WT$parity == 1, 1,
                               ifelse(PFAS_WT$parity > 1, 2, 0)))
PFAS_WT$smoke <- ifelse(PFAS_WT$smoke == "former", 0,
                       ifelse(PFAS_WT$smoke == "smoke preg", 1,
                              ifelse(PFAS_WT$smoke == "xnever", 2, 2)))
PFAS_WT$married <- ifelse(PFAS_WT$married == 1, 1, 0)
PFAS_WT$edu <- ifelse(PFAS_WT$edu == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_WT$bmi_cat <- as.factor(PFAS_WT$bmi_cat)
PFAS_WT$race <- as.factor(PFAS_WT$race)
PFAS_WT$income <- as.factor(PFAS_WT$income)
PFAS_WT$parity <- as.factor(PFAS_WT$parity)
PFAS_WT$smoke <- as.factor(PFAS_WT$smoke)
PFAS_WT$married <- as.factor(PFAS_WT$married)
PFAS_WT$edu <- as.factor(PFAS_WT$edu)

# CENTER AND SCALE CONTINUOUS VARIABLES, SYSTOLIC BP
PFAS_WT$age_s <- scale(PFAS_WT$age)
PFAS_WT$menar_s <- scale(PFAS_WT$menar)
PFAS_WT$fish_s <- scale(PFAS_WT$fish)
PFAS_WT$darkmeat_s <- scale(PFAS_WT$darkmeat)

# ##### TABE 1
# table1(~ age + menar + bmi + bmi_cat + race +  income + parity + smoke + 
#          married + edu + fish + darkmeat, data = PFAS_WT, overall = "Total")

```

```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####

###### CREATE MIXTURE OF PFAS
mixture_WT <- as.matrix(cbind(PFAS_WT$PFOS, PFAS_WT$PFOA, PFAS_WT$PFNA, PFAS_WT$PFHxS, 
                               PFAS_WT$MeFOSAA, PFAS_WT$EtFOSAA))

# RENAME VARIABLES IN MIXTURE
colnames(mixture_WT) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")

# LOG2-TRANSFORM MIXTURE
l2mixture_WT <- apply(mixture_WT, 2, log2)     

# SCALE MIXTURE VARIABLES TO THE MEAN
l2mixture_WT_z <- scale(l2mixture_WT)

##### SET THE OUTCOME
a_WT <- PFAS_WT$a_wt
c_WT <- PFAS_WT$c_wt

##### CREATE THE COVARIATE MATRIX
cov_WT <- as.matrix(cbind(PFAS_WT$age_s, PFAS_WT$menar_s, PFAS_WT$race, PFAS_WT$bmi_cat, 
                           PFAS_WT$parity, PFAS_WT$smoke, PFAS_WT$married, PFAS_WT$fish_s))

##### SET THE SEED
set.seed(1234)

##### CREATE KNOTS
knots_WT <- fields::cover.design(l2mixture_WT_z, nd = 110)$design

```

```{r}
##### BUILD BKMR MODELS
# # SIZE PARAMETER
# m1_WT <- kmbayes(y = a_WT, Z = l2mixture_WT_z, X = cov_WT, iter = 20000, family = "gaussian",
#                      verbose = FALSE, varsel = TRUE, knots = knots_WT)
# beep(sound = 5, expr = NULL)

# # VELOCITY PARAMETER
# m2_WT <- kmbayes(y = c_WT, Z = l2mixture_WT_z, X = cov_WT, iter = 20000, family = "gaussian",
#                      verbose = FALSE, varsel = TRUE, knots = knots_WT)
# beep(sound = 5, expr = NULL)

```

```{r}
# ##### SAVE WORKSPACE FOR SBP BKMR FUNCTIONS
# save(m1_WT, m2_WT,
#      file="C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/P2_BKMR.Rdata")

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
sel <- seq(0,20000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
# TracePlot(fit = m1_WT, par = "beta", sel = sel)
# TracePlot(fit = m2_WT, par = "beta", sel = sel)

##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_m1_WT <- seq(1200, 20000, by = 1)
# TracePlot(fit = m1_WT, par = "beta", sel = sel_m1_WT)
# TracePlot(fit = m1_WT, par = "sigsq.eps", sel = sel_m1_WT)

sel_m2_WT <- seq(1200, 20000, by = 1)
# TracePlot(fit = m2_WT, par = "beta", sel = sel_m2_WT)
# TracePlot(fit = m2_WT, par = "sigsq.eps", sel = sel_m2_WT)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# SIZE PARAMETER
summary(m1_WT)
ExtractPIPs(m1_WT, sel = sel_m1_WT)

# VELOCITY PARAMETER
summary(m2_WT)
ExtractPIPs(m2_WT, sel = sel_m2_WT)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
univar_mag <- PredictorResponseUnivar(fit = m1_WT, sel = sel_m1_WT, method = "approx")

# WEIGHT TRAJECTORY VELOCITY
univar_vel <- PredictorResponseUnivar(fit = m2_WT, sel = sel_m2_WT, method = "approx")



##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
uni1_WT <- ggplot(univar_mag, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) +
  geom_smooth(stat = "identity", colour = 'black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Weight traj magnitude (kg)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))

uni11_WT <- ggplot(univar_mag[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Weight traj mag (kg)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni12_WT <- ggplot(univar_mag[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Weight traj mag (kg)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni13_WT <- ggplot(univar_mag[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Weight traj mag (kg)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni14_WT <- ggplot(univar_mag[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Weight traj mag (kg)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni15_WT <- ggplot(univar_mag[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Weight traj mag (kg)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni16_WT <- ggplot(univar_mag[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Weight traj mag (kg)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni1_WT
uni11_WT
uni12_WT
uni13_WT
uni14_WT
uni15_WT
uni16_WT


# WEIGHT TRAJECTORY VELOCITY
uni2_WT <- ggplot(univar_vel, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) +
 geom_smooth(stat = "identity", colour = 'black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Weight traj velocity (%)") + 
 geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))

uni21_WT <- ggplot(univar_vel[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Weight traj velocity (%)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) +theme(text = element_text(size = 26.5))

uni22_WT <- ggplot(univar_vel[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Weight traj velocity (%)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni23_WT <- ggplot(univar_vel[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Weight traj velocity (%)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni24_WT <- ggplot(univar_vel[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Weight traj velocity (%)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni25_WT <- ggplot(univar_vel[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Weight traj velocity (%)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))

uni26_WT <- ggplot(univar_vel[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour = 'black') + theme_classic() + 
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Weight traj velocity (%)") + 
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 26.5))


uni2_WT
uni21_WT
uni22_WT
uni23_WT
uni24_WT
uni25_WT
uni26_WT

```

```{r}
##### PREDICT BIVARIATE EXPOSURE-RESPONSE CURVE TO ASSESS POTENTIAL INTERACTIONS
##### SUBESQUENTLY, PREDICT INTERACTIONS AMONG PFAS
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
bivar_mag <- PredictorResponseBivar(fit = m1_WT, min.plot.dist = 1, sel = sel_m1_WT, method = "approx")
interact_mag <- PredictorResponseBivarLevels(pred.resp.df = bivar_mag, Z = l2mixture_WT,
                                             both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_mag_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_mag, Z = l2mixture_WT,
                                                  both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WEIGHT TRAJECTORY VELOCITY
bivar_vel <- PredictorResponseBivar(fit = m2_WT, min.plot.dist = 1, sel = sel_m2_WT, method = "approx")
interact_vel <- PredictorResponseBivarLevels(pred.resp.df = bivar_vel, Z = l2mixture_WT,
                                             both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_vel_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_vel, Z = l2mixture_WT, 
                                                  both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))



##### PLOT BIVARIATE INTERACTIONS
##### NON-PARALLEL LINES WOULD INDICATE POTENTIAL INTERACTIONS
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
p_interact_mag <- ggplot(interact_mag, aes(z1, est)) + 
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size = 20),
               axis.title.y=element_text(angle=90, color='black', size = 20)) +
  xlab ("PFAS 1") +
  ylab ("Weight trajectory magnitude (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_mag


# WEIGHT TRAJECTORY VELOCITY
p_interact_vel <- ggplot(interact_vel, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size = 20),
               axis.title.y=element_text(angle=90, color='black', size = 20)) +
  xlab ("PFAS 1") +
  ylab ("Weight trajectory velocity (%)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vel 

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
overall_mag <- OverallRiskSummaries(fit = m1_WT, q.fixed = 0.50, sel = sel_m1_WT,
                                    method = "approx", qs = seq(0.25, 0.75, by = 0.05))

# WEIGHT TRAJECTORY VELOCITY
overall_vel <- OverallRiskSummaries(fit = m2_WT, q.fixed = 0.50, sel = sel_m2_WT,
                                    method = "approx", qs = seq(0.25, 0.75, by = 0.05))



##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
p_overall_mag <- ggplot(overall_mag, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Weight traj mag (kg)") +
               xlab("PFAS quantile") +
               theme_classic() + theme(
               axis.text.x = element_text(size = 25),
               axis.text.y = element_text(size = 25),
               axis.title.x = element_text(angle = 0, color = 'black', size = 25),
               axis.title.y = element_text(angle = 90, color = 'black', size = 25))
p_overall_mag


# WEIGHT TRAJECTORY VELOCITY
p_overall_vel <- ggplot(overall_vel, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Weight traj velocity (%)") +
               xlab("PFAS quantile") +
               theme_classic() + theme(
               axis.text.x = element_text(size = 25),
               axis.text.y = element_text(size = 25),
               axis.title.x = element_text(angle = 0, color = 'black', size = 25),
               axis.title.y = element_text(angle = 90, color = 'black', size = 25))
p_overall_vel

```

```{r}
##### ESTIMATE SINGLE PFAS EFFECT
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
singvar_mag <- SingVarRiskSummaries(fit = m1_WT, qs.diff = c(0.25, 0.75),
                                    q.fixed = c(0.25, 0.50, 0.75), sel = sel_m1_WT, method = "approx")
singvar_mag
singvar_mag2 <- SingVarRiskSummaries(fit = m1_WT, qs.diff = c(0.25, 0.75),
                                    q.fixed = c(0.50), sel = sel_m1_WT, method = "approx")
singvar_mag2
2.60319098 - 1.96*0.6353374
2.60319098 + 1.96*0.6353374
-1.98836622 - 1.96*0.4660087
-1.98836622 + 1.96*0.4660087

# > 2.60319098 - 1.96*0.6353374
# [1] 1.35793
# > 2.60319098 + 1.96*0.6353374
# [1] 3.848452
# > -1.98836622 - 1.96*0.4660087
# [1] -2.901743
# > -1.98836622 + 1.96*0.4660087
# [1] -1.074989


# WEIGHT TRAJECTORY VELOCITY
singvar_vel <- SingVarRiskSummaries(fit = m2_WT, qs.diff = c(0.25, 0.75),
                                    q.fixed = c(0.25, 0.50, 0.75), sel = sel_m2_WT, method = "approx")
singvar_vel
singvar_vel2 <- SingVarRiskSummaries(fit = m2_WT, qs.diff = c(0.25, 0.75),
                                    q.fixed = c(0.50), sel = sel_m2_WT, method = "approx")
singvar_vel2
3.3488319 - 1.96*2.905540
3.3488319 + 1.96*2.905540

-3.1973984 - 1.96*2.110555
-3.1973984 + 1.96*2.110555

3.7235200 - 1.96*2.366815
3.7235200 + 1.96*2.366815

# > 3.3488319 - 1.96*2.905540
# [1] -2.346026
# > 3.3488319 + 1.96*2.905540
# [1] 9.04369
# > 
# > -3.1973984 - 1.96*2.110555
# [1] -7.334086
# > -3.1973984 + 1.96*2.110555
# [1] 0.9392894
# > 
# > 3.7235200 - 1.96*2.366815
# [1] -0.9154374
# > 3.7235200 + 1.96*2.366815
# [1] 8.362477




##### PLOT SINGLE PFAS EFFECT
##### HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
p_singvar_mag <- ggplot(singvar_mag, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + 
  theme_bw() + theme(text = element_text(size = 23)) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "black", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight trajectory magnitude (kg)")
p_singvar_mag


# WEIGHT TRAJECTORY VELOCITY
p_singvar_vel <- ggplot(singvar_vel, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + 
  theme_bw() + theme(text = element_text(size = 23)) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "black", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight trajectory velocity (%)")
p_singvar_vel



# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
p_singvar_mag2 <- ggplot(singvar_mag2, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight trajectory magnitude (kg)")
p_singvar_mag2


# WEIGHT TRAJECTORY VELOCITY
p_singvar_vel2 <- ggplot(singvar_vel2, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight trajectory velocity (%)")
p_singvar_vel2

```

```{r}
##### UNIVARIATE INTERACTIONS AMONG PFAS
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
overall_interact_mag <- SingVarIntSummaries(fit = m1_WT, qs.diff = c(0.25, 0.75), 
                                            qs.fixed = c(0.25, 0.75), sel = sel_m1_WT)

# WEIGHT TRAJECTORY VELOCITY
overall_interact_vel <- SingVarIntSummaries(fit = m2_WT, qs.diff = c(0.25, 0.75), 
                                            qs.fixed = c(0.25, 0.75), sel = sel_m2_WT)



##### PLOT UNIVARIATE INTERACTIONS
# WEIGHT TRAJECTORY SIZE (MAGNITUDE)
p_overall_interact_mag <- ggplot(overall_interact_mag, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +theme(text = element_text(size = 25)) +
  geom_hline(yintercept = 0, lty = 2, color = "red", linewidth = 1) + coord_flip() +
  ylab("Weight trajectory magnitude (kg)") +
  xlab("Plasma PFAS")
p_overall_interact_mag


# WEIGHT TRAJECTORY VELOCITY
p_overall_interact_vel <- ggplot(overall_interact_vel, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 25)) +
  geom_hline(yintercept = 0, lty = 2, color = "red", linewidth = 1) + coord_flip() +
  ylab("Weight trajectory velocity (%)") +
  xlab("Plasma PFAS")
p_overall_interact_vel

```
