#####                                                       #####
##### EVALUATE DISTRIBUTION OF VARIABLES AND CREATE TABLE 1 #####
#####                                                       #####

```{r}
##### LOAD PACKAGES
library("tidyverse")
library("dplyr")
library("table1")
library("gtools")
library("corrplot")
library("Hmisc")

```

```{r}
##### LOAD DATASET
PFAS <-read.csv("C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/PFAS_COMP.csv")
PFAS_X <-read.csv("C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/PFAS_X.csv")

```

```{r}
##### TRANSFORM PFAS TO OBSERVE SHAPE OF DISTRIBUTION
PFAS$LNPFOS <- log(PFAS$PFOS)
PFAS$LNPFOA <- log(PFAS$PFOA)
PFAS$LNPFNA <- log(PFAS$PFNA)
PFAS$LNPFHxS <- log(PFAS$PFHxS)
PFAS$LNMeFOSAA <- log(PFAS$MeFOSAA)
PFAS$LNEtFOSAA <- log(PFAS$EtFOSAA)

PFAS$L2PFOS <- log(PFAS$PFOS, 2)
PFAS$L2PFOA <- log(PFAS$PFOA, 2)
PFAS$L2PFNA <- log(PFAS$PFNA, 2)
PFAS$L2PFHxS <- log(PFAS$PFHxS, 2)
PFAS$L2MeFOSAA <- log(PFAS$MeFOSAA, 2)
PFAS$L2EtFOSAA <- log(PFAS$EtFOSAA, 2)

```

```{r}
##### DESCRIBE PFAS DISTRIBUTION
hist(PFAS$PFOS)
hist(PFAS$PFOA)
hist(PFAS$PFNA)
hist(PFAS$PFHxS)
hist(PFAS$MeFOSAA)
hist(PFAS$EtFOSAA)

# DESCRIBE LNPFAS DISTRIBUTION
hist(PFAS$LNPFOS)
hist(PFAS$LNPFOA)
hist(PFAS$LNPFNA)
hist(PFAS$LNPFHxS)
hist(PFAS$LNMeFOSAA)
hist(PFAS$LNEtFOSAA)

# DESCRIBE L2PFAS DISTRIBUTION
hist(PFAS$L2PFOS)
hist(PFAS$L2PFOA)
hist(PFAS$L2PFNA)
hist(PFAS$L2PFHxS)
hist(PFAS$L2MeFOSAA)
hist(PFAS$L2EtFOSAA)

```

```{r}
##### CONVERT DAYS TO YEARS
# DAYS POSTPARTUM
PFAS$DPP_RAV1 <- PFAS$DPP_RAV1/365
PFAS$DPP_RAV2 <- PFAS$DPP_RAV2/365
PFAS$DPP_RAV3 <- PFAS$DPP_RAV3/365
PFAS$DPP_RAV4 <- PFAS$DPP_RAV4/365

# AGE AT WEIGHT MEASUREMENTS
PFAS$AGE_RAV1 <- PFAS$AGE_RAV1/365 
PFAS$AGE_RAV2 <- PFAS$AGE_RAV2/365 
PFAS$AGE_RAV3 <- PFAS$AGE_RAV3/365 
PFAS$AGE_RAV4 <- PFAS$AGE_RAV3/365 

```

```{r}
##### DESCRIBE DISTRIBUTION OF OUTCOME MEASURES
hist(PFAS$WT_RAV1)
hist(PFAS$WT_RAV2)
hist(PFAS$WT_RAV3)
hist(PFAS$WT_RAV4)

```

```{r}
##### RENAME
PFAS$age_enroll <- PFAS$age_mom_enroll_d
PFAS$menar <- PFAS$mom_firstperiod_12y
PFAS$bmi <- PFAS$bmi_mom_prepreg_d
PFAS$race <- PFAS$race2_mom_epi_epia_d
PFAS$income <- PFAS$gt70k
PFAS$parity <- PFAS$parity_d
PFAS$smoke <- PFAS$smokpreg_final_d
PFAS$married <- PFAS$married_cohab
PFAS$edu <- PFAS$coll_grad


##### RE-LABEL 
PFAS$bmi_cat <- ifelse(PFAS$bmi <18.5, 0,
                         ifelse(PFAS$bmi >=18.5 & PFAS$bmi < 25.0, 1, 
                                ifelse(PFAS$bmi >=25.0 & PFAS$bmi < 30.0, 2, 
                                       ifelse(PFAS$bmi >=30.0 & PFAS$bmi < 35.0, 3,
                                              ifelse(PFAS$bmi >=35.0, 4, NA)))))
PFAS$race <- ifelse(PFAS$race == "white", 0,
                      ifelse(PFAS$race == "black", 1,
                             ifelse(PFAS$race == "hispa", 2,
                                    ifelse(PFAS$race == "asian", 3,
                                           ifelse(PFAS$race == "other", 4, 4)))))
PFAS$income <- ifelse(PFAS$income == 1, 1, 0)
PFAS$parity <- ifelse(PFAS$parity == 0, 0,
                        ifelse(PFAS$parity == 1, 1,
                               ifelse(PFAS$parity > 1, 2, 0)))
PFAS$smoke <- ifelse(PFAS$smoke == "former", 0,
                       ifelse(PFAS$smoke == "smoke preg", 1,
                              ifelse(PFAS$smoke == "xnever", 2, 2)))
PFAS$married <- ifelse(PFAS$married == 1, 1, 0)
PFAS$edu <- ifelse(PFAS$edu == 1, 1, 0)


##### REFACTOR
PFAS$bmi_cat <- factor(PFAS$bmi_cat,
                         levels = c(0, 1, 2, 3, 4),
                         labels = c("Underweight (< 18.5)", "Normal weight (18.5 to 24.9)", 
                                    "Overweight (25.0 to 29.9)", "Obesity (30.0 to 34.9)", 
                                    "Extremely obesity (>= 35)"))
PFAS$race <- factor(PFAS$race,
                      levels = c(0, 1, 2, 3, 4),
                      labels = c("White", "Black", "Hispanic", "Asian", "Other/More than 1 race"))
PFAS$income <- factor(PFAS$income,
                        levels = c(0, 1),
                        labels = c(" <= $70,000", "> $70,000"))
PFAS$parity <- factor(PFAS$parity,
                        levels = c(0, 1, 2),
                        labels = c("0", "1", ">= 2"))
PFAS$smoke <- factor(PFAS$smoke,
                       levels = c(0, 1, 2),
                       labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS$married <- factor(PFAS$married,
                         levels = c(0, 1),
                         labels = c("No", "Yes"))
PFAS$edu <- factor(PFAS$edu,
                     levels = c(0, 1),
                     labels = c(" < college degree", ">= college degree"))


##### LABEL
label(PFAS$age_enroll) <- "Maternal age at enrollment"
label(PFAS$menar) <- "Age at first menarche"
label(PFAS$bmi) <- "Pre-pregnancy BMI"
label(PFAS$bmi_cat) <- "Pre-pregnancy BMI"
label(PFAS$race) <- "Race/Ethnicity"
label(PFAS$income) <- "Annual household income"
label(PFAS$parity) <- "Parity"
label(PFAS$smoke) <- "Smoking status"
label(PFAS$married) <- "Married or cohabitating"
label(PFAS$edu) <- "Education"


##### ADD UNITS
units(PFAS$age_enroll)  <- "years"
units(PFAS$menar) <- "years"
units(PFAS$bmi)  <- "kg/m2"
units(PFAS$bmi_cat)  <- "kg/m2"

##### TABE 1
table1(~ age_enroll + menar + bmi + bmi_cat + race +  income + parity + smoke + 
         married + edu, data = PFAS, overall = "Total")

```

```{r}
##### EXCLUSION DATASET #####

##### RENAME
PFAS_X$age_enroll <- PFAS_X$age_mom_enroll_d
PFAS_X$menar <- PFAS_X$mom_firstperiod_1
PFAS_X$bmi <- PFAS_X$bmi_mom_prepreg_d
PFAS_X$race <- PFAS_X$race2_mom_epi_epia_d
PFAS_X$income <- PFAS_X$gt70k
PFAS_X$parity <- PFAS_X$pari_d
PFAS_X$smoke <- PFAS_X$smokpreg_final_d
PFAS_X$married <- PFAS_X$married_cohab
PFAS_X$edu <- PFAS_X$coll_grad


##### RE-LABEL 
PFAS_X$bmi_cat <- ifelse(PFAS_X$bmi <18.5, 0,
                         ifelse(PFAS_X$bmi >=18.5 & PFAS_X$bmi < 25.0, 1, 
                                ifelse(PFAS_X$bmi >=25.0 & PFAS_X$bmi < 30.0, 2, 
                                       ifelse(PFAS_X$bmi >=30.0 & PFAS_X$bmi < 35.0, 3,
                                              ifelse(PFAS_X$bmi >=35.0, 4, NA)))))
PFAS_X$race <- ifelse(PFAS_X$race == "white", 0,
                      ifelse(PFAS_X$race == "black", 1,
                             ifelse(PFAS_X$race == "hispa", 2,
                                    ifelse(PFAS_X$race == "asian", 3,
                                           ifelse(PFAS_X$race == "other", 4, 4)))))
PFAS_X$income <- ifelse(PFAS_X$income == 1, 1, 0)
PFAS_X$parity <- ifelse(PFAS_X$parity == 0, 0,
                        ifelse(PFAS_X$parity == 1, 1,
                               ifelse(PFAS_X$parity > 1, 2, 0)))
PFAS_X$smoke <- ifelse(PFAS_X$smoke == "former", 0,
                       ifelse(PFAS_X$smoke == "smoke preg", 1,
                              ifelse(PFAS_X$smoke == "xnever", 2, 2)))
PFAS_X$married <- ifelse(PFAS_X$married == 1, 1, 0)
PFAS_X$edu <- ifelse(PFAS_X$edu == 1, 1, 0)


##### REFACTOR
PFAS_X$bmi_cat <- factor(PFAS_X$bmi_cat,
                         levels = c(0, 1, 2, 3, 4),
                         labels = c("Underweight (< 18.5)", "Normal weight (18.5 to 24.9)", 
                                    "Overweight (25.0 to 29.9)", "Obesity (30.0 to 34.9)", 
                                    "Extremely obesity (>= 35)"))
PFAS_X$race <- factor(PFAS_X$race,
                      levels = c(0, 1, 2, 3, 4),
                      labels = c("White", "Black", "Hispanic", "Asian", "Other/More than 1 race"))
PFAS_X$income <- factor(PFAS_X$income,
                        levels = c(0, 1),
                        labels = c(" <= $70,000", "> $70,000"))
PFAS_X$parity <- factor(PFAS_X$parity,
                        levels = c(0, 1, 2),
                        labels = c("0", "1", ">= 2"))
PFAS_X$smoke <- factor(PFAS_X$smoke,
                       levels = c(0, 1, 2),
                       labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS_X$married <- factor(PFAS_X$married,
                         levels = c(0, 1),
                         labels = c("No", "Yes"))
PFAS_X$edu <- factor(PFAS_X$edu,
                     levels = c(0, 1),
                     labels = c(" < college degree", ">= college degree"))


##### LABEL
label(PFAS_X$age_enroll) <- "Maternal age at enrollment"
label(PFAS_X$menar) <- "Age at first menarche"
label(PFAS_X$bmi) <- "Pre-pregnancy BMI"
label(PFAS_X$bmi_cat) <- "Pre-pregnancy BMI"
label(PFAS_X$race) <- "Race/Ethnicity"
label(PFAS_X$income) <- "Annual household income"
label(PFAS_X$parity) <- "Parity"
label(PFAS_X$smoke) <- "Smoking status"
label(PFAS_X$married) <- "Married or cohabitating"
label(PFAS_X$edu) <- "Education"


##### ADD UNITS
units(PFAS_X$age_enroll)  <- "years"
units(PFAS_X$menar) <- "years"
units(PFAS_X$bmi)  <- "kg/m2"
units(PFAS_X$bmi_cat)  <- "kg/m2"


##### TABE 1
table1(~ age_enroll + menar + bmi + bmi_cat + race +  income + parity + smoke + 
         married + edu, data = PFAS_X, overall = "Total")

```

```{r}
##### PFAS DISTRIBUTION TABLE
summary(PFAS$PFOS)
summary(PFAS$PFOA)
summary(PFAS$PFNA)
summary(PFAS$PFHxS)
summary(PFAS$MeFOSAA)
summary(PFAS$EtFOSAA)

##### ASSESS DETECTION FREQUENCIES
table(PFAS$LOD_PFOS)
table(PFAS$LOD_PFOA)
table(PFAS$LOD_PFNA)
table(PFAS$LOD_PFHxS)
table(PFAS$LOD_MeF)
table(PFAS$LOD_EtF)

##### PFAS CORRELATION MATRIX
PFAS_corr <- PFAS[ , c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")]
p_corr <- cor(PFAS_corr)
round(p_corr, 2)

corrplot(p_corr, type = "upper", order = "hclust", method = "circle",
         tl.col = "black", tl.srt = 45, col = COL2('RdBu', 10), addCoef.col = 'black')

```

```{r}
##### OUTCOMES DISTRIBUTION TABLE
# VISIT 1 (6 MONTHS PP)
summary(PFAS$DPP_RAV1)
summary(PFAS$AGE_RAV1)
summary(PFAS$WT_RAV1)

# VISIT 2 (EARLY CHILDHOOD)
summary(PFAS$DPP_RAV2)
summary(PFAS$AGE_RAV2)
summary(PFAS$WT_RAV2)

# VISIT 3 (MID CHILDHOOD)
summary(PFAS$DPP_RAV3)
summary(PFAS$AGE_RAV3)
summary(PFAS$WT_RAV3)

# VISIT 4 (EARLY TEEN)
summary(PFAS$DPP_RAV4)
summary(PFAS$AGE_RAV4)
summary(PFAS$WT_RAV4)

##### LABEL
label(PFAS$DPP_RAV1) <- "Time postpartum, Visit 1"
label(PFAS$DPP_RAV2) <- "Time postpartum, Visit 2"
label(PFAS$DPP_RAV3) <- "Time postpartum, Visit 3"
label(PFAS$DPP_RAV4) <- "Time postpartum, Visit 4"
label(PFAS$AGE_RAV1) <- "Maternal age, Visit 1"
label(PFAS$AGE_RAV2) <- "Maternal age, Visit 2"
label(PFAS$AGE_RAV3) <- "Maternal age, Visit 3"
label(PFAS$AGE_RAV4) <- "Maternal age, Visit 4"
label(PFAS$WT_RAV1) <- "Weight, Visit 1"
label(PFAS$WT_RAV2) <- "Weight, Visit 2"
label(PFAS$WT_RAV3) <- "Weight, Visit 3"
label(PFAS$WT_RAV4) <- "Weight, Visit 4"

##### ADD UNITS
units(PFAS$DPP_RAV1) <- "years"
units(PFAS$DPP_RAV2) <- "years"
units(PFAS$DPP_RAV3) <- "years"
units(PFAS$DPP_RAV4) <- "years"
units(PFAS$AGE_RAV1) <- "years"
units(PFAS$AGE_RAV2) <- "years"
units(PFAS$AGE_RAV3) <- "years"
units(PFAS$AGE_RAV4) <- "years"
units(PFAS$WT_RAV1) <- "kg"
units(PFAS$WT_RAV2) <- "kg"
units(PFAS$WT_RAV3) <- "kg"
units(PFAS$WT_RAV4) <- "kg"


table1(~ DPP_RAV1 + AGE_RAV1 + WT_RAV1 + DPP_RAV2 + AGE_RAV2 + WT_RAV2 + 
         DPP_RAV3 + AGE_RAV3 + WT_RAV3 + DPP_RAV4 + AGE_RAV4 + WT_RAV4, data = PFAS, overall = "Total")

```

```{r}
##### SAVE DATASET
write.csv(PFAS, file = "C:/Users/jarva/Desktop/James-Todd Lab/P2.PFASandWeightTrajectories/Data/PFAS.csv", row.names = T)

```
